### ISSUE TITLE
AssertionError? 

### ISSUE THREAD

**Issue by azraar** [maszhongming/MatchSum#11]
Hi  maszhong 
 
 I'm getting the following error?
can you please help me 

 
(tf) lili@melody:~/MatchSum$ CUDA_VISIBLE_DEVICES=0,1,3 python train_matching.py --mode=train --encoder=roberta --save_path=./roberta --gpus=0,1,3
Training process of MatchSum !!!
Start loading datasets !!!
Finished in 0:02:24.464620
Information of dataset is:
In total 2 datasets:
	train has 287084 instances.
	val has 13367 instances.

Devices is:
[0, 1, 3]
Traceback (most recent call last):
  File "train_matching.py", line 150, in <module>
    train_model(args)
  File "train_matching.py", line 70, in train_model
    assert args.batch_size % len(devices) == 0
AssertionError

**Comment by maszhongming** [comment]
Hi, azraar. This assertion means that the `batch_size` should be a multiple of the number of GPUs you use. If you use three GPUs for training, you can adjust the `batch_size` to 6 or 12.
