### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by guowenying111** [maszhongming/MatchSum#13]
Thanks for your work, I wonder how reddit datasets gain labels used to bertsum model, I used the original  bertsum process code, but the labels I gain is different with yours on reddit dataset. I will appreciate if you can help me.

**Comment by maszhongming** [comment]
Thank you for your interest in our work. We also used the original bertsum process code to obtain labels, and we used the TIFU-long version of Reddit in this paper. Are these settings the same as your experiment?
In addition, if the performance difference of the labels you get is not large, it may have little effect on the performance of the final model.
