### ISSUE TITLE
段错误(吐核)

### ISSUE THREAD

**Issue by hahasdnu1029** [maszhongming/MatchSum#14]
Hi maszhong
I'm getting the following error?
can you please help me

Training process of MatchSum !!!
Start loading datasets !!!
Finished in 0:02:05.141637
Information of dataset is:
In total 2 datasets:
	train has 287084 instances.
	val has 13367 instances.

Devices is:
[0, 1, 2, 3]
段错误(吐核)

**Comment by ShibataGenjiro** [comment]
Hi,

I think you met the segmentation fault (core dumped) error.

I also met this problem and I solved it by updating the transformers(2.5.1) to the 3.0.1.
(Other dependencies: python 3.6.10,      PyTorch 1.4.0,     fastNLP 0.5.0   pyrouge 0.1.3   rouge 1.0.0 )
