### ISSUE TITLE
关于MarginRankingLoss 

### ISSUE THREAD

**Issue by elevenofji** [maszhongming/MatchSum#15]
计算candidate loss时是否应该是range(1,n)而不是range(1,n-1)？为什么可以忽略rank最大和rank最小对应的的candidate loss呢

**Comment by maszhongming** [comment]
你好，这里的 i 表示的是几倍的 margin，例如一个长度为 10 的数组，最后一个数与第一个数之间是 9 倍的间隔，所以这里是 n-1。

**Comment by elevenofji** [comment]
你好！可能是我理解的问题，range（1，n-1）应该只能取到n-2吧，最后一个数和第一个数对应的loss似乎是没有计算到，所以我才有这个疑问。

**Comment by maszhongming** [comment]
抱歉，我们曾经修复过这个 bug，但最终放出来了错误的版本。我们现在已经再次修正了，非常感谢你的提醒！
另外，由于只漏算了很小部分的 loss，在我们的实验中这个错误对最终性能几乎不会产生影响。

**Comment by elevenofji** [comment]
好的，我只是查看loss计算方式时对此步有一些疑惑，非常感谢作者的及时回复！

**Comment by elevenofji** [comment]
作者你好，在阅读中我还有两个问题想要询问，
第一个问题就是Table1中的Ext，以及Table 2中Ext、Sel、Size，它们的大小和范围是通过什么方式选择的？是经验得到的吗？
第二个问题：除了从实验结果证明summary-level得到的summary更好，有其他的方式证明summary-level的summary一定是比sentence-level的summary更加符合人对一个“好的摘要”的定义吗？（尽管论文提到前者可以提取pearl-summary，但pearl-summary为什么就是“更好的摘要”呢？）
如果是论文3.3部分可以证明这一点，那么summary-level score和sentence-level score是同一个**量级**的得分吗？这个inherent gap 会不会是因为两种分数计算方式的差异造成它们不是一个量级的分数所导致的？

**Comment by maszhongming** [comment]
你好，
关于第一个问题，Ext 一般是根据数据集中的 gold summary 长度决定的，如果 gold summary 平均有三句左右，Ext 就会取 3；Sel 和 Size 则是希望取尽可能多的长度为 # Ext 左右的候选摘要集合（在不爆显存的前提下）；
关于第二个问题，关于如何定义一个“好的摘要”也是一个研究热点，但不在本文的研究范畴。这里我们使用通用的 ROUGE 分数高的摘要来当做一个更好的摘要，但需要注意的是，我们这里的 sentence-level score 和 summary-level score 是可以替换成任何指标的，如果有更好的指标可以用于评价摘要，更加符合人对“好的摘要”的定义，是可以直接将这里的  score 全部替换为新的指标；
最后，关于量级的问题，在计算 inherent gap 时，我们会首先挑选出 sentence-level score 和 summary-level score 最高的两个候选摘要，再计算这两个候选摘要之间 summary-level score 的差异，关于这点我们没有在原文中写清楚，我们会做进一步的修改和说明，非常抱歉！

**Comment by elevenofji** [comment]
好的，非常感谢！
