### ISSUE TITLE
Constructing input data for BERT-EXT on Multi-News.

### ISSUE THREAD

**Issue by hukuda222** [maszhongming/MatchSum#20]
Hi, thank you for publishing your interesting research and source code. 
Now I am trying to construct input data for BERT-EXT on Multi-News. I have one question.

First of all, I checked the test_multinews.jsonl in [here](https://drive.google.com/file/d/1PnFCwqSzAUr78uEcA_Q15yupZ5bTAQIb/view).
Next, I created token ids to be entered into BERT-EXT from "text" using transformers.BertTokenizer. After doing that, I noticed a discrepancy between the number of sentences in the first 512 tokens and the length of "label". Why do they differ? 

Perhaps you have your own preprocess, can you give us some details?

**Comment by maszhongming** [comment]
Is there a big difference between the number of sentences and the length of "label"?  For BertExt, you need to add [SEP] and [CLS] as separators between sentences, but for MatchSum, you don't need to add these. I think if the difference is not very big, it may be caused by this.

**Comment by hukuda222** [comment]
Thanks for replying. It's certainly not a big problem with the slightly different number of sentences, but I'm having trouble reproducing the ORACLE in your paper. The ORACLE score in your paper is 49.06/21.54/44.27, but when I tried to reproduce it, it was 43.90/19.13/39.47.

I followed https://github.com/nlpyang/PreSumm for pre-processing and rouge calculations. Probably your pre-processing and rouge calculation method are different from Pre-Summ, so I'd like to know the details.

I think there are many sentences that are excluded because I couldn't reproduce ORACLE by extracting all sentences with label set to 1.

**Comment by maszhongming** [comment]
Did you use our dataset for testing? I am not familiar with how PreSumm calculates ORACLE, but the data I released (e.g., test_multinews.jsonl) already contains `label`, you can directly extract the sentences with `label` 1 as the summary to reproduce the results in our paper.

**Comment by hukuda222** [comment]
Yes, I directly used the data you provided. I'm interested in ORACLE, not MATCH-ORACLE. I think ORACLE can be reproduced by extracting the sentence from the "text" that corresponds to the "label" of your prepared data. And I don't think the number of sentences to be extracted according to "label" is always 9.

**Comment by maszhongming** [comment]
Sorry, I just edited the reply, you can refer to the above. If you still cannot reproduce, I can provide the relevant code.

**Comment by hukuda222** [comment]
Unfortunately, I couldn't reproduce it, so I'd like you to share the relevant source code in some way.

**Comment by maszhongming** [comment]
You can try the following code:
```python
import json
import sys
import os
from os.path import join, exists
import subprocess as sp
import tempfile
import logging

from pyrouge.utils import log
from pyrouge import Rouge155

DEC_PATH = './dec' # path to the extracted summaries
REF_PATH = './ref' # path to the reference summaries
data_path = '/path/to/test_multinews.jsonl'
_ROUGE_PATH = '/path/to/RELEASE-1.5.5'

# create ref and dec folders
if exists(REF_PATH):
    os.system('rm -r {}'.format(REF_PATH))
os.makedirs(REF_PATH)
if exists(DEC_PATH):
    os.system('rm -r {}'.format(DEC_PATH))
os.makedirs(DEC_PATH)

def load_data(path):
    data = []
    with open(path) as f:
        for line in f:
            data.append(json.loads(line))
    return data

# calculate ROUGE score
def get_rouge():
    log.get_global_console_logger().setLevel(logging.WARNING)
    dec_pattern = '(\d+).dec'
    ref_pattern = '#ID#.ref'
    dec_dir = DEC_PATH
    ref_dir = REF_PATH
    cmd = '-c 95 -r 1000 -n 2 -m'
    with tempfile.TemporaryDirectory() as tmp_dir:
        Rouge155.convert_summaries_to_rouge_format(
            dec_dir, join(tmp_dir, 'dec'))
        Rouge155.convert_summaries_to_rouge_format(
            ref_dir, join(tmp_dir, 'ref'))
        Rouge155.write_config_static(
            join(tmp_dir, 'dec'), dec_pattern,
            join(tmp_dir, 'ref'), ref_pattern,
            join(tmp_dir, 'settings.xml'), system_id=1
        )
        cmd = (join(_ROUGE_PATH, 'ROUGE-1.5.5.pl')
            + ' -e {} '.format(join(_ROUGE_PATH, 'data'))
            + cmd
            + ' -a {}'.format(join(tmp_dir, 'settings.xml')))
        output = sp.check_output(cmd.split(' '), universal_newlines=True)
    print(output)

# load data
data = load_data(data_path)
n = len(data)
print('Total {} files !!!'.format(n))

# write reference
for i in range(n):
    with open(join(REF_PATH, '{}.ref'.format(i)), 'w') as f:
        for sent in data[i]['summary']:
            print(sent, file=f)

# write extracted summary
for i in range(n):
    with open(join(DEC_PATH, '{}.dec'.format(i)), 'w') as f:
        for j in range(len(data[i]['label'])):
            if data[i]['label'][j] == 1:
                print(data[i]['text'][j], file=f)

# calculate ORACLE
print('\nORACLE is:')
get_rouge()

# remove dec and ref
os.system('rm -r {}'.format(REF_PATH))
os.system('rm -r {}'.format(DEC_PATH))
```
The result I got is:
```
---------------------------------------------
1 ROUGE-1 Average_R: 0.42856 (95%-conf.int. 0.42564 - 0.43156)
1 ROUGE-1 Average_P: 0.60404 (95%-conf.int. 0.60100 - 0.60732)
1 ROUGE-1 Average_F: 0.49056 (95%-conf.int. 0.48809 - 0.49319)
---------------------------------------------
1 ROUGE-2 Average_R: 0.18650 (95%-conf.int. 0.18365 - 0.18967)
1 ROUGE-2 Average_P: 0.26924 (95%-conf.int. 0.26524 - 0.27366)
1 ROUGE-2 Average_F: 0.21537 (95%-conf.int. 0.21224 - 0.21887)
---------------------------------------------
1 ROUGE-L Average_R: 0.38618 (95%-conf.int. 0.38338 - 0.38910)
1 ROUGE-L Average_P: 0.54623 (95%-conf.int. 0.54299 - 0.54966)
1 ROUGE-L Average_F: 0.44272 (95%-conf.int. 0.44023 - 0.44538)
```

**Comment by hukuda222** [comment]
Thank you so much. 
It didn't work a bit with the one you sent me, but I was able to reproduce it with the pre-summ one. Thank you for taking the time to do this.
