### ISSUE TITLE
100% accuracy with one candidate 

### ISSUE THREAD

**Issue by kubzdel** [maszhongming/MatchSum#21]
I'm not sure if this is a bug or it is how this algorithm works. I have my own dataset with 'text' and 'summary'. Desired summary is known from the beginning and it consists of few 'text' sentences.  In this case 'candidate' is the same as 'summary' so in get_candidate I skip calculating rouge scores and just set indices = [sent_id] . Then when training with this data I get loss close to 0 and 100% ROUGE on train and val set immediately.

Is it a desired effect or this algorithms always needs some candidates which aren't extracted exactly from 'summary' but from 'text'?

Previously I used PreSum for the same tasks and data and got satisfactory results.

**Comment by maszhongming** [comment]
Using our model requires you to provide some candidate summaries. When there is only one candidate summary, it will result in 100% accuracy.

How to train our model on your data may refer to [issue#4](https://github.com/maszhongming/MatchSum/issues/4) and [issue#5](https://github.com/maszhongming/MatchSum/issues/5).

**Comment by kubzdel** [comment]
Thank you for the answer, it's just as I thought.
