### ISSUE TITLE
Generated Summaries

### ISSUE THREAD

**Issue by suchanun** [maszhongming/MatchSum#3]
Hi, the generated summaries [here](https://drive.google.com/file/d/11_eSZkuwtK4bJa_L3z2eblz4iwRXOLzU/view) contain the reference summaries (.ref files) and the model generated summaries (.dec files). I wonder if there are original text file of the article? Is there a way to get the original text files associated with the summaries?

Thanks!

**Comment by maszhongming** [comment]
There are download links for all datasets in README, you can find the dataset you want, and the `text` field in the test set is the original text.

**Comment by suchanun** [comment]
Thank you, just wondering if there is the associated non-processed original text? (like with no new line characters taken out, and can see text as original paragraphs)

**Comment by maszhongming** [comment]
Sorry, we don’t have non-processed original text for each dataset here. Maybe you can download the original version of each dataset to see if it contains the format you want.
