### ISSUE TITLE
End-to-end summarization

### ISSUE THREAD

**Issue by ghost** [maszhongming/MatchSum#5]
I'm a bit confused by the forward pass of the model :

https://github.com/maszhongming/MatchSum/blob/966095de9bb53ed541d1f9e8c03778ca9034ab5f/model.py#L20

Why do we need the `summary_ids` ? At inference time we don't have access to the gold summary, so how can we use MatchSum at inference time ?

**=> Given only the article, how to use MatchSum to produce a summary ?** 

---

As far as I understood, the pipeline would be :

1. Use `BertExt` (or any other sentence classifier) to extract k=5 sentences from the article
2. Compute all possible summaries combinations (C(5, 2) + C(5, 3))
3. Using MatchSum, compute the cosine similarity between the original article and each summaries computed in 2.
4. Take the summary with the best similarity.

Am I right ?
If so we need to rewrite the MatchSum class to get as input `text_ids` and a list of `cand_ids`, right ?

**Comment by maszhongming** [comment]
Yes, your understanding of our pipeline is very correct. In fact, although we input `summary_id` during the inference and calculate `summary_score`, we do not actually use them afterwards. 

**Given only the article, how to use MatchSum to produce a summary?**
As to this question, during the test phase, our code will first select the semantically closest summary, and then calculate the ROUGE score with the gold summary, so we default to include a gold summary in your data. If your data does not contain a gold summary, you can choose any random word as the summary, and then use our script to process your data. It is worth noting that this will still calculate a ROUGE score, you can ignore it, and the output of the model will be stored in the folder `./result`.
