### ISSUE TITLE
Difficulties to reproduce score End-to-end

### ISSUE THREAD

**Issue by astariul** [maszhongming/MatchSum#6]
I'm trying to reproduce the score on CNN/DM, using Matchum, with End-to-end summarization.

Here is the code I use :

```python
# BertExt, return 5 most salient sentences from a list of sentences
sentences = self.extractor(documents, k=5, block_trigram=False)

text_id = tokenizer.batch_encode_plus([" ".join(d) for d in documents], return_tensors="pt", pad_to_max_length=True, max_length=tokenizer.model_max_length)["input_ids"]
cand_id = []
all_summaries = []
for sen in sentences:     # Iterate over batches
	summaries = list(combinations(sen, 2))
        summaries += list(combinations(sen, 3))
	summaries = [" ".join(s) for s in summaries]       # Create summary from list of sentences
	all_summaries.append(summaries)

	cand_id.append(torch.cat([tokenizer.encode_plus(s, max_length=tokenizer.model_max_length, return_tensors="pt", pad_to_max_length=True)["input_ids"] for s in summaries]))
cand_id = torch.stack(cand_id)

text_id = text_id.to(device)
cand_id = cand_id.to(device)
scores = self.match_sum(text_id, cand_id)
_, selected_sum = scores.max(-1)      # Take the summary with the best score (semantically similar to the document) 

return [summaries[selected] for summaries, selected in zip(all_summaries, selected_sum)]
```

My score is :
```
---------------------------------------------
1 ROUGE-1 Average_R: 0.48578 (95%-conf.int. 0.48274 - 0.48869)
1 ROUGE-1 Average_P: 0.36573 (95%-conf.int. 0.36313 - 0.36839)
1 ROUGE-1 Average_F: 0.39591 (95%-conf.int. 0.39383 - 0.39817)
---------------------------------------------
1 ROUGE-2 Average_R: 0.21714 (95%-conf.int. 0.21426 - 0.21986)
1 ROUGE-2 Average_P: 0.16260 (95%-conf.int. 0.16041 - 0.16501)
1 ROUGE-2 Average_F: 0.17620 (95%-conf.int. 0.17390 - 0.17840)
---------------------------------------------
1 ROUGE-L Average_R: 0.43988 (95%-conf.int. 0.43690 - 0.44274)
1 ROUGE-L Average_P: 0.33191 (95%-conf.int. 0.32945 - 0.33446)
1 ROUGE-L Average_F: 0.35889 (95%-conf.int. 0.35677 - 0.36091)
```

which is even lower than BertExt...

Any idea what I'm doing wrong ?

**Comment by maszhongming** [comment]
Sorry, I am a little confused here. May I ask `self.extractor` and `self.match_sum` here are pre-trained models, so you did an end-to-end test process? Or is this a training process, and you want to train `self.extractor` and `self.match_sum` at the same time?

**Comment by astariul** [comment]
`self.extractor` is a trained model (on CNN/DM) similar to `BertExt`.
`self.match_sum` is your checkpoint, trained on CNN/DM using RoBERTa.

And yes you're right, I'm trying to get the results with an end-to-end test process.

**Comment by maszhongming** [comment]
I found no problem in the code you posted.

I have two questions:
1. Is the performance of `self.extractor` similar to BertExt on CNN / DM?
2. Do you use the tokenizer for RoBERTa? BERT and RoBERTa have different vocabularies.

**Comment by astariul** [comment]
Thank you very much for taking the time reviewing my code.

1. Performance of `self.extractor` are similar to BertExt : **43.33 / 20.59 / 39.62** (It's basically the same architecture but I used ELECTRA instead of BERT).

2. Yes, I used RoBERTa tokenizer, initialized like this :
```python
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
```

However I use the latest version of `transformers` package, but I think it should not matter (no breaking changes).

Thanks again. I will try more and update this issue if I find anything..

**Comment by astariul** [comment]
I found my problem :

In your code, you compute the `attention_mask` dynamically in the forward pass :

https://github.com/maszhongming/MatchSum/blob/966095de9bb53ed541d1f9e8c03778ca9034ab5f/model.py#L25

And you assume the `[PAD]` token ID is `0`.

But in my case, as mentioned earlier, I used `RobertaTokenizer`. And it seems the `[PAD]` token ID is different than yours :

```
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
print(tokenizer.pad_token_id)        # Print `1`
```

So I passed the `attention_mask` computed by the Tokenizer to your model (I modified the forward pass so the `attention_mask` is not computed there).

---

Results are much better !

`43.93 / 20.79 / 39.97`

_I still can't reproduce your paper results, but it may be due to my extractor, which is not the same as yours. Anyway using your architecture / model improved greatly the score of my vanilla extractor !_

---

As a side question, **why do you use `0` as `[PAD]` token ?** It seems that the official `[PAD]` token is `1`.

**Comment by maszhongming** [comment]
Thank you very much for pointing out this problem!
For Roberta, we do ignore that `[PAD]` token ID is `1` and we are terribly sorry for any inconvenience so caused.

We will fix the bug and release a new version of RoBERTa model soon.

**Comment by maszhongming** [comment]
Hi, we have fixed the bug and released a new version of RoBERTa model now, which has similar performance to the previous version and can correctly identify the `[PAD]` token. Maybe you can get further performance improvement by using this new version model.
