### ISSUE TITLE
Evaluation of raw text

### ISSUE THREAD

**Issue by timsuchanek** [maszhongming/MatchSum#7]
First of all, great work!

If I would like to evaluate my own raw text with one of the pre-trained models that you just released, how would I go about that?
Would I have to put them into the `jsonl` format first or could I directly pass in the text somehow into the model?

Thanks!

**Comment by suchanun** [comment]
Hi, I asked the same question [here](https://github.com/maszhongming/MatchSum/issues/4) and got answers.

**Comment by timsuchanek** [comment]
Thanks! So from what I understood, you need to provide your own candidates of sentences there? I would like to just post the raw text.

**Comment by maszhongming** [comment]
Thanks suchanun for the explanation. 

I'm sorry if you only post the raw text you will not be able to use our model directly. You need to provide some candidate sentences (using BertExt or other methods), and then use our script to get the candidate summaries.
